import TypedEmitter from "typed-emitter";
import { SessionEventCallbacks, AgentEventCallbacks } from "./events";
import { SessionState, SessionConfig } from "./types";
import { ConnectionQuality } from "../QualityIndicator";
import { VoiceChat } from "../VoiceChat";
declare const LiveAvatarSession_base: new () => TypedEmitter<SessionEventCallbacks & AgentEventCallbacks>;
export declare class LiveAvatarSession extends LiveAvatarSession_base {
    private readonly sessionClient;
    private readonly config;
    private readonly room;
    private readonly _voiceChat;
    private readonly connectionQualityIndicator;
    private _sessionInfo;
    private _sessionEventSocket;
    private _state;
    private _remoteAudioTrack;
    private _remoteVideoTrack;
    constructor(sessionAccessToken: string, config?: SessionConfig);
    get state(): SessionState;
    get connectionQuality(): ConnectionQuality;
    get voiceChat(): VoiceChat;
    get maxSessionDuration(): number | null;
    start(): Promise<void>;
    stop(): Promise<void>;
    keepAlive(): Promise<void>;
    attach(element: HTMLMediaElement): void;
    message(message: string): void;
    repeat(message: string): void;
    repeatAudio(audio: string): void;
    startListening(): void;
    stopListening(): void;
    interrupt(): void;
    private trackEvents;
    private connectWebSocket;
    private setupWebSocketManagement;
    private handleWebSocketMessage;
    private handleWebSocketDisconnect;
    private configureSession;
    private set state(value);
    private cleanup;
    private postStop;
    private handleRoomDisconnect;
    private sendCommandEvent;
    private generateEventId;
    private sendCommandEventToWebSocket;
    private assertConnected;
}
export {};
